name = "discordworker"
main = "src/worker.ts"
compatibility_date = "2023-11-18"

workers_dev = false

tail_consumers = [
  {service = "cf-tail-logger"},
]

[[queues.consumers]]
queue = "discordqueue"

[[queues.producers]]
queue = "discordqueue"
binding = "DQUEUE"