name = "discordworker"
main = "src/worker.ts"
compatibility_date = "2023-11-18"

workers_dev = false

[[queues.consumers]]
queue = "discordqueue"

[[queues.producers]]
queue = "discordqueue"
binding = "DQUEUE"