name = "discordworker"
main = "src/worker.ts"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

[observability]
enabled = true 

[[queues.consumers]]
queue = "discordqueue"

[[queues.producers]]
queue = "discordqueue"
binding = "DQUEUE"